<h1>Login</h1>

<?php $form = $this->form; ?>

<?php echo $this->form()->openTag($form); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('username')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('password')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('submit')); ?>
</div>

<?php echo $this->form()->closeTag($form); ?>

