<h1>Your Profile</h1>

<?php echo $this->gravatar($this->user->getEmailAddress()); ?>

<div><?php echo $this->user->getDisplayName(); ?></div>
<div><?php echo $this->user->getEmailAddress(); ?></div>

<div><?php echo $this->user->getUsername(); ?></div>
<div><?php echo $this->user->getDomain(); ?></div>

<div><?php echo $this->user->getId(); ?></div>

<hr>
<a class="btn btn-sm btn-default" href="<?php echo $this->url('changepassword'); ?>">Change Password</a>
<a class="btn btn-sm btn-primary" href="<?php echo $this->url('logout'); ?>">Logout</a>