<h1>Your Profile</h1>

<div class="media">
    <div class="media-left">
      <?php echo $this->gravatar($this->Identity()->getEmailAddress()); ?>
    </div>
    <div class="media-body">
        <h4 class="media-heading"><?php echo $this->Identity()->getDisplayName(); ?></h4>
        <div><?php echo $this->Identity()->getEmailAddress(); ?></div>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-4">
        <table class="table table-condensed table-striped">
            <tbody>
                <tr>
                    <th>Username</th>
                    <td><?php echo $this->Identity()->getUsername(); ?></td>
                <tr>
                    <th>Domain</th>
                    <td><?php echo $this->Identity()->getDomain(); ?></td>
                </tr>
            </tbody>
        </table>
        
    </div>
</div>

<hr>
<a class="btn btn-sm btn-default" href="<?php echo $this->url('changepassword'); ?>">Change Password</a>
<a class="btn btn-sm btn-primary" href="<?php echo $this->url('logout'); ?>">Logout</a>
